---
- name: Install PHP
  action: apt pkg={{item}} state=installed
  with_items:
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - php5-curl
    - php5-gd
    - php5-json
    - php5-xmlrpc
  notify: restart apache
