# Beams v0.3.0
# Copyright (c) 2014-2015 Peter McKay
# Free to use under the MIT license.

FROM roscoelabs/beams:latest
MAINTAINER: pete@roscoelabs.com
#RUN add-apt-repository ppa:nginx/development
#RUN apt-get update && apt-get install nginx
RUN echo "Eureka! API gateway is up and running."
