# Beams v0.3.0
# Copyright (c) 2014-2016 Peter McKay
# Free to use under the MIT license.


FROM nginx
MAINTAINER Peter McKay <pete@roscoelabs.com>

#Add self-signed security cert to package...
#Add config files to nginx, working off old Beams versions...
#Restart nginx daemon...

RUN echo "API gateway is up! Eureka!"
CMD 
