---
- name: Install Apache
  action: apt pkg={{item}} state=installed
  with_items:
    - apache2
    - apache2-utils

- name: Enable mod_rewrite
  file:
    src: "/etc/apache2/mods-available/rewrite.load"
    dest: "/etc/apache2/mods-enabled/rewrite.load"
    state: link

- name: Symlink Known site into web directory
  file: src=/home/vagrant/Known dest=/var/www/Known state=link

- name: Add known site configuration
  template:
    src: "known.conf"
    dest: "/etc/apache2/sites-available/known.conf"
    owner: root
    group: root
    mode: 0644

- name: Add known to sites-enabled
  file:
    src: "/etc/apache2/sites-available/known.conf"
    dest: "/etc/apache2/sites-enabled/known.conf"
    state: link

- name: Remove default Apache site
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: restart apache
