---
# This playbook contains common plays that will be run on all nodes.

- name: Update all packages
  apt: upgrade=dist update_cache=yes

- name: Install base packages
  action: apt pkg={{item}} state=installed
  with_items:
    - ntp
    - htop

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started
  tags: ntp

- name: Ensure NTP is running and enabled at system start.
  service: >
    name=ntp
    state=started
    enabled=yes